// Produtos iniciais para importar no banco (botão "Importar produtos atuais")
window.SIZES_DEFAULT = ["PP", "P", "M", "G", "GG"];
window.SEED = [
  { ordem: 1, categoria: "Macaquinhos", nome: "Macaquinho Sculpt", codigo: "NNV-MAC-001", preco: 69.9, preco_antigo: null, tag: "Novo", esgotado: false, sugestao_look: false, nota: "", tamanhos: window.SIZES_DEFAULT, cores: [{ name: "Vermelho", hex: "#a5121b", sizes: ["G"] }, { name: "Azul", hex: "#2f6fb0", sizes: ["P"] }, { name: "Preto", hex: "#141414", sizes: ["M"] }], imagens: ["prod-macaquinho.jpg", "prod-macaquinho-back.jpg", "prod-mac-preto.jpg", "prod-mac-azul.jpg", "prod-mac-stack.jpg"] },
  { ordem: 2, categoria: "Conjuntos", nome: "Conjunto Flare Power", codigo: "NNV-CJ-002", preco: 159.9, preco_antigo: null, tag: "Best-seller", esgotado: true, sugestao_look: false, nota: "", tamanhos: window.SIZES_DEFAULT, cores: [{ name: "Preto", hex: "#141414" }], imagens: ["prod-flare-front.jpg", "prod-flare-back.jpg"] },
  { ordem: 3, categoria: "Sugestões de looks", nome: "Look Cinza — Short + Baby Tee", codigo: "NNV-LK-004", preco: null, preco_antigo: null, tag: "Novo", esgotado: true, sugestao_look: true, nota: "Short e baby tee vendidos separadamente.", tamanhos: ["Único"], cores: [{ name: "Cinza", hex: "#8a8683" }], imagens: ["prod-conjunto-cinza.jpg"] },
  { ordem: 4, categoria: "Sugestões de looks", nome: "Look Azul — Short Ribbed + Regata", codigo: "NNV-LK-005", preco: null, preco_antigo: null, tag: "Novo", esgotado: false, sugestao_look: true, nota: "Short Ribbed + Regata Azul — peças vendidas separadamente.", tamanhos: ["Único"], cores: [{ name: "Azul", hex: "#a9c7e0" }], imagens: ["prod-short-front.jpg", "prod-short-back.jpg"] },
  { ordem: 5, categoria: "Baby Tee", nome: "Baby Tee", codigo: "NNV-BBY-006", preco: 35.9, preco_antigo: null, tag: "Novo", esgotado: false, sugestao_look: false, nota: "", tamanhos: ["M"], cores: [{ name: "Preto", hex: "#141414" }], imagens: ["prod-baby-tee.jpg"] },
  { ordem: 6, categoria: "Regatas", nome: "Regata", codigo: "NNV-REG-007", preco: 39.9, preco_antigo: null, tag: "Novo", esgotado: false, sugestao_look: false, nota: "", tamanhos: window.SIZES_DEFAULT, cores: [{ name: "Azul", hex: "#2f6fb0", sizes: ["M"] }, { name: "Preto", hex: "#141414", sizes: ["M"] }], imagens: ["prod-regata-flat.jpg", "prod-regata-azul.jpg"] },
  { ordem: 7, categoria: "Shorts", nome: "Short Ribbed", codigo: "NNV-SH-008", preco: 49.9, preco_antigo: null, tag: "Novo", esgotado: false, sugestao_look: false, nota: "", tamanhos: ["P", "M"], cores: [{ name: "Preto", hex: "#141414", sizes: ["P", "M"] }, { name: "Marrom", hex: "#5b3a29", sizes: ["P", "M"] }, { name: "Azul", hex: "#2f6fb0", sizes: ["P", "M"] }, { name: "Roxo", hex: "#7d1f6a", sizes: ["P", "M"] }], imagens: ["prod-shorts.jpg", "prod-short-azul.jpg", "prod-short-marrom.jpg", "prod-short-roxo.jpg"] },
  { ordem: 8, categoria: "Leggings", nome: "Legging Azul Marinho", codigo: "NNV-LEG-009", preco: 49.9, preco_antigo: null, tag: "Novo", esgotado: false, sugestao_look: false, nota: "", tamanhos: ["G"], cores: [{ name: "Azul marinho", hex: "#1b2440", sizes: ["G"] }, { name: "Preto", hex: "#141414", sizes: ["G"] }], imagens: ["prod-legging-marinho.jpg", "prod-legging-flat.jpg"] },
  { ordem: 9, categoria: "Conjuntos", nome: "Conjunto Verde Militar", codigo: "NNV-CJ-010", preco: 119.9, preco_antigo: null, tag: "Best-seller", esgotado: true, sugestao_look: false, nota: "", tamanhos: ["Único"], cores: [{ name: "Verde militar", hex: "#4d5a3a" }], imagens: ["prod-conjunto-verde.jpg"] },
  { ordem: 10, categoria: "Conjuntos", nome: "Conjunto Top Azul + Short Marrom", codigo: "NNV-CJ-011", preco: 76.9, preco_antigo: null, tag: "Novo", esgotado: false, sugestao_look: false, nota: "", tamanhos: ["Único"], cores: [{ name: "Azul/Marrom", hex: "#2f6fb0" }], imagens: ["prod-conjunto-azul-marrom.jpg"] },
  { ordem: 11, categoria: "Conjuntos", nome: "Conjunto Marrom", codigo: "NNV-CJ-012", preco: 76.9, preco_antigo: null, tag: "Novo", esgotado: false, sugestao_look: false, nota: "", tamanhos: ["Único"], cores: [{ name: "Marrom", hex: "#8a6b52" }], imagens: ["prod-conjunto-marrom.jpg", "prod-conjunto-marrom-flat.jpg"] },
  { ordem: 12, categoria: "Acessórios", nome: "Bolsa de Treino", codigo: "NNV-BAG-013", preco: 69.9, preco_antigo: null, tag: "Novo", esgotado: false, sugestao_look: false, nota: "", tamanhos: ["Único"], cores: [{ name: "Preto", hex: "#141414" }], imagens: ["prod-bolsa.jpg"] },
];
